APPLICATION=SNode
PFLAGS=-I%T/lib/Counters \
	-I$(TINYGALS_TOSDIR)/lib/BigMsg \
	-I$(TINYGALS_TOSDIR)/lib/Pot \
	-I$(TINYGALS_TOSDIR)/lib/Counters 
PFLAGS += -DBIGMSG_RETRY_COUNT=1
include ../Makerules
